FPGA_IMAGE_VERSION := 0.1
AWS_FPGA_VERSION := v1.4.5

DEPENDENCIES := bsg_manycore bsg_f1 bsg_ip_cores

BSG_MANYCORE_HASH := 107dd5a
BSG_F1_HASH       := fd55921
BSG_IP_CORES_HASH := ae9c7d8
AGFI_ID := agfi-0d347cdf0ae5a90fb
